"""added Products table

Revision ID: 056c89860466
Revises: 1a90af5ac981
Create Date: 2023-08-17 14:11:15.359827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056c89860466'
down_revision = '1a90af5ac981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
