"""empty message

Revision ID: 641e0ccdeaaf
Revises: 056c89860466
Create Date: 2023-08-20 00:40:33.760545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641e0ccdeaaf'
down_revision = '056c89860466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('confirm_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_pre_orders_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pre_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_orders')
    # ### end Alembic commands ###
