"""added specs column to products

Revision ID: 744c7b93bddd
Revises: 10e6dc832202
Create Date: 2023-08-28 13:16:52.586712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744c7b93bddd'
down_revision = '10e6dc832202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specs', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('specs')

    # ### end Alembic commands ###
